[package]
name = "toondb-nodejs-native"
version = "0.3.6"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["async"] }
napi-derive = "2"

[dependencies.toondb-storage]
path = "../../toondb/toondb-storage"

[build-dependencies]
napi-build = "2"
